const cities = {
    "Kosovë": [
        "Deçan",
        "Dragash",
        "Drenas",
        "Ferizaj",
        "Fushë Kosovë",
        "Gjakovë",
        "Gjilan",
        "Graçanicë",
        "Han i Elezit",
        "Istog",
        "Junik",
        "Kamenicë",
        "Kaçanik",
        "Klinë",
        "Kllokot",
        "Leposaviq",
        "Lipjan",
        "Malishevë",
        "Mamushë",
        "Mitrovicë Veriore",
        "Mitrovicë",
        "Novobërdë",
        "Obiliq",
        "Partesh",
        "Pejë",
        "Podujevë",
        "Prishtinë",
        "Prizren",
        "Rahovec",
        "Ranillug",
        "Shtime",
        "Shtërpcë",
        "Skenderaj",
        "Suharekë",
        "Viti",
        "Vushtrri",
        "Zubin Potok",
        "Zveçan"
    ],
    "Shqipëri": [
        "Bajram Curri",
        "Ballsh",
        "Berat",
        "Bilisht",
        "Bulqizë",
        "Burrel",
        "Cërrik",
        "Çorovodë",
        "Delvinë",
        "Divjakë",
        "Durrës",
        "Elbasan",
        "Ersekë",
        "Fier",
        "Fushë Arrëz",
        "Fushë Krujë",
        "Gjirokastër",
        "Gramsh",
        "Himarë",
        "Kamëz",
        "Kavajë",
        "Konispol",
        "Koplik",
        "Korçë",
        "Krastë",
        "Krujë",
        "Krumë",
        "Kukës",
        "Kuçovë",
        "Këlcyrë",
        "Kërrabë",
        "Laç",
        "Leskovik",
        "Lezhë",
        "Libohovë",
        "Librazhd",
        "Lushnjë",
        "Maliq",
        "Mamurras",
        "Memaliaj",
        "Milot",
        "Orikum",
        "Patos",
        "Peqin",
        "Peshkopi",
        "Pogradec",
        "Poliçan",
        "Pukë",
        "Përmet",
        "Përrenjas",
        "Rogozhinë",
        "Roskovec",
        "Rrëshen",
        "Rubik",
        "Sarandë",
        "Selenicë",
        "Shijak",
        "Shkodër",
        "Shtërmen",
        "Shëngjin",
        "Tepelenë",
        "Tiranë",
        "Ura Vajgurore",
        "Vlorë",
        "Vorë"
    ],
    "Maqedoni e Veriut": [
        "Berovë",
        "Bogdanca",
        "Brod",
        "Dellçevë",
        "Demir Hisari",
        "Demir Kapia",
        "Dibër",
        "Gjevgjeli",
        "Gostivar",
        "Kamenicë",
        "Kavadar",
        "Koçan",
        "Kratovë",
        "Kriva Pallanka",
        "Krushevë",
        "Kumanovë",
        "Kërçovë",
        "Manastir",
        "Negotinë",
        "Ohër",
        "Peçevë",
        "Prilep",
        "Probishtip",
        "Radovisht",
        "Resnjë",
        "Shkup",
        "Shtip",
        "Strugë",
        "Strumicë",
        "Sveti Nikolla",
        "Tetovë",
        "Vallandovë",
        "Veles",
        "Vinicë"
    ]
}

export default cities;